"""empty message

Revision ID: 351aa45dc518
Revises: 24abb03488be
Create Date: 2024-01-17 09:41:04.694708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '351aa45dc518'
down_revision = '24abb03488be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artist_name', sa.String(), nullable=True))
        batch_op.drop_column('aritist_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aritist_name', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('artist_name')

    # ### end Alembic commands ###
